services:
  kafka:
    image: bitnami/kafka:4.0
    container_name: kafka
    ports:
      - "9092:9092"   # External Kafka access
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_KRAFT_CLUSTER_ID=cluster-ec2-12345
    volumes:
      - kafka_data:/bitnami/kafka

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  producer:
    build:
      context: ./producer
    container_name: producer
    depends_on:
      - kafka
    restart: always

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    depends_on:
      - kafka
      - mongo
    restart: always

  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard
    ports:
      - "8501:8501"
    depends_on:
      - mongo
    restart: always

volumes:
  kafka_data:
  mongo_data:
